name: Lint workflow files

on:
  push:
    paths:
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'

permissions:
  pull-requests: write
  contents: read

jobs:
  actionlint:
    uses: fac/shared-workflows/.github/workflows/actionlint.yml@main
    secrets: inherit
